# Node.js & Yarn
FROM node:10.15.1-alpine as node

RUN apk add --no-cache --virtual .ruby-builddeps bash curl \
  && curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4 \
  && apk del .ruby-builddeps

# Ruby & Bundler & postgresql-client
FROM ruby:2.6.5-alpine

COPY --from=node /usr/local/bin/node /usr/local/bin/node
COPY --from=node /opt/yarn-* /opt/yarn
RUN ln -fs /opt/yarn/bin/yarn /usr/local/bin/yarn

ENV RUN_PACKAGES="nodejs postgresql postgresql-dev tzdata" \
    DEV_PACKAGES="build-base curl-dev gcc libc-dev libxml2-dev linux-headers make" \
    CHROME_PACKAGES="chromium chromium-chromedriver dbus mesa-dri-swrast ttf-freefont udev wait4ports xorg-server xvfb zlib-dev"

RUN apk --update --no-cache add ${RUN_PACKAGES} \
  && apk --update --no-cache add ${DEV_PACKAGES} \
  && cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime \
  && apk del --purge tzdata

ENV ENTRYKIT_VERSION 0.4.0

# Entrykit & ChromeDriver
RUN wget https://github.com/progrium/entrykit/releases/download/v${ENTRYKIT_VERSION}/entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && tar -xvzf entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && rm entrykit_${ENTRYKIT_VERSION}_Linux_x86_64.tgz \
  && mv entrykit /bin/entrykit \
  && chmod +x /bin/entrykit \
  && entrykit --symlink \
  && apk --update --no-cache add ${CHROME_PACKAGES}

# 作業ディレクトリの作成、設定
RUN mkdir /ketsuatsu_app
WORKDIR /ketsuatsu_app

# bundle install & Delete Unnecessary Packages_and_Cache & Copy File
COPY Gemfile /ketsuatsu_app/Gemfile
COPY Gemfile.lock /ketsuatsu_app/Gemfile.lock
RUN gem install bundler --version 2.1.2 \
  && bundle install --path vendor/bundle \
  && find vendor/bundle/ruby -path '*/gems/*/ext/*/Makefile' -exec dirname {} \; | xargs -n1 -P$(nproc) -I{} make -C {} clean \
  && apk del ${DEV_PACKAGES}
COPY . /ketsuatsu_app

ENTRYPOINT [ \
  "prehook", "bundle install -j3 --path vendor/bundle", "--", \
  "prehook", "ruby -v", "--", \
  "prehook", "node -v", "--" \
]
