version: '3'

services:
  db:
    image: postgres:11.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Tokyo
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: bundle exec rails server -b 0.0.0.0
