version: '3'

services:
  db:
    image: postgres:11.4-alpine
    container_name: ketsuatsu_app_db
    environment:
      POSTGRES_PASSWORD: postgres
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    container_name: ketsuatsu_app_web
    command: bundle exec rails server -b 0.0.0.0
    ports:
      - "3000:3000"
    depends_on:
      - db
