version: 2.1
jobs:
  rubocop:
    working_directory: ~/ketsuatsu_app
    docker:
      - image: circleci/ruby:2.6.5
    steps:
      - checkout
      - restore_cache:
          keys:
            - gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gemfiles-{{ .Branch }}-
            - gemfiles-master-
      - run:
          name: bundle config --local path vendor/bundle
          command: |
            gem install bundler -v 2.1.2
            bundle config --local path vendor/bundle
      - run:
          name: bundle install
          command: bundle check || bundle install --jobs=8 --clean
      - run:
          name: Run rubocop
          command: bundle exec rubocop --parallel
      - save_cache:
          key: gemfiles-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

  heroku_deploy:
    working_directory: ~/ketsuatsu_app
    docker:
      - image: sue445/heroku-cli
    steps:
      - checkout
      - build-tools/install-ci-tools
      - jq/install
      - run:
          name: Identify who I am
          command: echo 'export MY_EMAIL=`heroku auth:whoami | tail -n 1`' >> $BASH_ENV
      - run:
          name: Deploy
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/mikanntaroh-ketsuatsu.git master

orbs:
  build-tools: circleci/build-tools@2.6.3
  jq: circleci/jq@2.0.2
workflows:
  version: 2.1
  build:
    jobs:
      - rubocop
      - heroku_deploy:
          requires:
            - rubocop
